name: Docker Image CI

env:
  IMAGE_REPO: carlory
  REGISTER: ghcr.io
  IMAGE_ROOT_PATH: docker
  BUILD_PLATFORM: linux/amd64
  REGISTER_USER: ${{ github.actor }}
  REGISTER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            VERSION=latest
          fi
          echo ::set-output name=VERSION::${VERSION}

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login registry
        run: |
          echo "${{ env.REGISTER_PASSWORD }}" | docker login ${{ env.REGISTER }} -u ${{ env.REGISTER_USER }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master

      - name: Build & Pushing firefly-controller-manager image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.IMAGE_ROOT_PATH }}/Dockerfile
          labels: |-
            org.opencontainers.image.source=https://github.com/${{ env.IMAGE_REPO }}/firefly
            org.opencontainers.image.revision=${{ github.sha }}
          platforms: ${{ env.BUILD_PLATFORM }}
          build-args: |
            VERSION=${{ steps.get_version.outputs.VERSION }}
          tags: ${{ env.REGISTER }}/${{ env.IMAGE_REPO }}/firefly-controller-manager:${{ steps.get_version.outputs.VERSION }}
          push: true
          github-token: ${{ env.REGISTER_PASSWORD }}

      - name: Build & Pushing firefly-webhook image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.IMAGE_ROOT_PATH }}/Dockerfile.webhook
          labels: |-
            org.opencontainers.image.source=https://github.com/${{ env.IMAGE_REPO }}/firefly
            org.opencontainers.image.revision=${{ github.sha }}
          platforms: ${{ env.BUILD_PLATFORM }}
          build-args: |
            VERSION=${{ steps.get_version.outputs.VERSION }}
          tags: ${{ env.REGISTER }}/${{ env.IMAGE_REPO }}/firefly-webhook:${{ steps.get_version.outputs.VERSION }}
          push: true
          github-token: ${{ env.REGISTER_PASSWORD }}

      - name: Build & Pushing firefly-karmada-manager image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.IMAGE_ROOT_PATH }}/Dockerfile.firefly-karmada-manager
          labels: |-
            org.opencontainers.image.source=https://github.com/${{ env.IMAGE_REPO }}/firefly
            org.opencontainers.image.revision=${{ github.sha }}
          platforms: ${{ env.BUILD_PLATFORM }}
          build-args: |
            VERSION=${{ steps.get_version.outputs.VERSION }}
          tags: ${{ env.REGISTER }}/${{ env.IMAGE_REPO }}/firefly-karmada-manager:${{ steps.get_version.outputs.VERSION }}
          push: true
          github-token: ${{ env.REGISTER_PASSWORD }}
